import { Component, computed } from '@angular/core';
import { RouterLink } from '@angular/router';

import { I18nService } from '../core/i18n.service';
import { LanguagePickerComponent } from '../components/language-picker.component';
import { SeoService } from '../core/seo.service';

const copy = {
  'pt-BR': { navProduct:'Produto', navSecurity:'Segurança', navPrice:'Preço', enter:'Entrar', start:'Criar conta grátis', mainNavigation:'Navegação principal', flowLabel:'Fluxo de assinatura', freeFive:'5 grátis', noCard:'Sem cartão', demoSignedBy:'ASSINADO POR', demoHash:'Hash verificado · 14:32', demoIntegrity:'Documento íntegro', sponsorLink:'SIB — abrir site', eyebrow:'ASSINATURAS SEM COMPLICAÇÃO', title:'Assine documentos com clareza, segurança e validade.', lead:'Envie PDFs, convide signatários e acompanhe cada etapa. As evidências ficam incorporadas ao documento assinado.', primary:'Começar com 5 assinaturas grátis', secondary:'Ver como funciona', trust:'Feito para documentos importantes', trustCopy:'Identidade, data, dispositivo, IP e hash do arquivo reunidos em uma trilha de evidências verificável.', step1:'Envie seu PDF', step2:'Convide as pessoas', step3:'Acompanhe e comprove', feature1:'Carimbo visual no PDF', feature2:'Autenticação em dois fatores', feature3:'Histórico e evidências', plans:'Planos para cada momento', plansHelp:'As assinaturas dos documentos estão incluídas. O limite mensal considera os arquivos enviados pela conta.', base:'Essencial', intermediate:'Profissional', team:'Equipe', enterprise:'Empresarial', enterpriseHelp:'Precisa de uma solução personalizada para sua empresa?', enterpriseFeature:'Volume, usuários, fluxo e atendimento sob medida', perMonth:'/mês por conta', currencies:'BRL · USD · EUR · JPY', baseFiles:'Até 20 arquivos por mês', intermediateFiles:'Até 80 arquivos por mês', professionalAccounts:'Até 3 contas', teamAccounts:'Até 10 contas', teamFiles:'Até 200 arquivos por mês', teamAnnual:'R$ 1.499,90 por ano', signaturesIncluded:'Assinaturas eletrônicas incluídas', emailIncluded:'Envio de solicitações por e-mail', choosePlan:'Começar grátis', talkToSales:'Falar com a Rubrica', cta:'Seu próximo documento pode estar assinado hoje.', supporters:'Apoiadores', supportersHelp:'Organizações que apoiam o desenvolvimento do Rubrica.', contact:'Contato', privacy:'Privacidade', terms:'Termos de uso', deletion:'Exclusão de dados', rights:'Rubrica. Documentos assinados, decisões registradas.' },
  en: { navProduct:'Product', navSecurity:'Security', navPrice:'Pricing', enter:'Sign in', start:'Create free account', mainNavigation:'Main navigation', flowLabel:'Signature flow', freeFive:'5 free', noCard:'No card required', demoSignedBy:'SIGNED BY', demoHash:'Verified hash · 14:32', demoIntegrity:'Document intact', sponsorLink:'SIB — open website', eyebrow:'SIGNATURES WITHOUT FRICTION', title:'Sign documents with clarity, security and confidence.', lead:'Upload PDFs, invite signers and follow every step. Evidence is embedded into the signed document.', primary:'Start with 5 free signatures', secondary:'See how it works', trust:'Built for important documents', trustCopy:'Identity, date, device, IP and file hash combined into a verifiable evidence trail.', step1:'Upload your PDF', step2:'Invite people', step3:'Track and verify', feature1:'Visual stamp on the PDF', feature2:'Two-factor authentication', feature3:'History and evidence', plans:'Plans for every stage', plansHelp:'Document signatures are included. The monthly allowance counts files uploaded by the account.', base:'Essential', intermediate:'Professional', team:'Team', enterprise:'Enterprise', enterpriseHelp:'A Rubrica solution tailored to your company’s processes.', enterpriseFeature:'Custom workflow, volume and support', perMonth:'/month per account', currencies:'BRL · USD · EUR · JPY', baseFiles:'Up to 20 files per month', intermediateFiles:'Up to 80 files per month', professionalAccounts:'Up to 3 accounts', teamAccounts:'Up to 10 accounts', teamFiles:'Up to 200 files per month', teamAnnual:'R$ 1,499.90 per year', signaturesIncluded:'Electronic signatures included', emailIncluded:'Email signature requests', choosePlan:'Start free', talkToSales:'Talk to Rubrica', cta:'Your next document could be signed today.', supporters:'Supporters', supportersHelp:'Organizations supporting Rubrica’s development.', contact:'Contact', privacy:'Privacy', terms:'Terms of use', deletion:'Data deletion', rights:'Rubrica. Signed documents, recorded decisions.' },
  es: { navProduct:'Producto', navSecurity:'Seguridad', navPrice:'Precios', enter:'Entrar', start:'Crear cuenta gratis', mainNavigation:'Navegación principal', flowLabel:'Flujo de firma', freeFive:'5 gratis', noCard:'Sin tarjeta', demoSignedBy:'FIRMADO POR', demoHash:'Hash verificado · 14:32', demoIntegrity:'Documento íntegro', sponsorLink:'SIB — abrir sitio web', eyebrow:'FIRMAS SIN COMPLICACIONES', title:'Firma documentos con claridad, seguridad y confianza.', lead:'Sube archivos PDF, invita firmantes y acompaña cada etapa. Las evidencias quedan incorporadas al documento firmado.', primary:'Comenzar con 5 firmas gratis', secondary:'Ver cómo funciona', trust:'Creado para documentos importantes', trustCopy:'Identidad, fecha, dispositivo, IP y hash del archivo reunidos en un registro verificable.', step1:'Sube tu PDF', step2:'Invita a las personas', step3:'Acompaña y comprueba', feature1:'Sello visual en el PDF', feature2:'Autenticación de dos factores', feature3:'Historial y evidencias', plans:'Planes para cada etapa', plansHelp:'Las firmas de documentos están incluidas. El límite mensual cuenta los archivos subidos por la cuenta.', base:'Esencial', intermediate:'Profesional', team:'Equipo', enterprise:'Empresarial', enterpriseHelp:'Una solución Rubrica adaptada a los procesos de su empresa.', enterpriseFeature:'Flujo, volumen y atención personalizados', perMonth:'/mes por cuenta', currencies:'BRL · USD · EUR · JPY', baseFiles:'Hasta 20 archivos por mes', intermediateFiles:'Hasta 80 archivos por mes', professionalAccounts:'Hasta 3 cuentas', teamAccounts:'Hasta 10 cuentas', teamFiles:'Hasta 200 archivos por mes', teamAnnual:'R$ 1.499,90 al año', signaturesIncluded:'Firmas electrónicas incluidas', emailIncluded:'Envío de solicitudes por correo', choosePlan:'Comenzar gratis', talkToSales:'Hablar con Rubrica', cta:'Tu próximo documento puede estar firmado hoy.', supporters:'Colaboradores', supportersHelp:'Organizaciones que apoyan el desarrollo de Rubrica.', contact:'Contacto', privacy:'Privacidad', terms:'Términos de uso', deletion:'Eliminación de datos', rights:'Rubrica. Documentos firmados, decisiones registradas.' },
  'ja-JP': { navProduct:'製品', navSecurity:'セキュリティ', navPrice:'料金', enter:'ログイン', start:'無料アカウント作成', mainNavigation:'メインナビゲーション', flowLabel:'署名フロー', freeFive:'無料5件', noCard:'カード不要', demoSignedBy:'署名者', demoHash:'ハッシュ検証済み · 14:32', demoIntegrity:'文書の完全性を確認済み', sponsorLink:'SIB — ウェブサイトを開く', eyebrow:'シンプルな電子署名', title:'明確で安全、信頼できる電子署名。', lead:'PDFをアップロードし、署名者を招待して進捗を確認。証拠情報は署名済み文書に組み込まれます。', primary:'無料5件から始める', secondary:'仕組みを見る', trust:'大切な文書のために', trustCopy:'本人情報、日時、端末、IP、ファイルハッシュを検証可能な証拠として記録します。', step1:'PDFを送信', step2:'署名者を招待', step3:'追跡・確認', feature1:'PDF上の署名スタンプ', feature2:'二要素認証', feature3:'履歴と証拠', plans:'用途に合わせたプラン', plansHelp:'文書への電子署名は含まれます。月間上限はアカウントがアップロードしたファイル数です。', base:'エッセンシャル', intermediate:'プロフェッショナル', team:'チーム', enterprise:'エンタープライズ', enterpriseHelp:'企業の業務に合わせたRubricaソリューション。', enterpriseFeature:'個別のワークフロー、利用量、サポート', perMonth:'／月・アカウント', currencies:'BRL · USD · EUR · JPY', baseFiles:'月20ファイルまで', intermediateFiles:'月80ファイルまで', professionalAccounts:'最大3アカウント', teamAccounts:'最大10アカウント', teamFiles:'月200ファイルまで', teamAnnual:'年額 R$ 1,499.90', signaturesIncluded:'電子署名を含む', emailIncluded:'メールで署名依頼を送信', choosePlan:'無料で始める', talkToSales:'Rubricaに相談', cta:'次の文書を今日署名しませんか。', supporters:'サポーター', supportersHelp:'Rubricaの開発を支援する組織です。', contact:'お問い合わせ', privacy:'プライバシー', terms:'利用規約', deletion:'データ削除', rights:'Rubrica。署名された文書、記録された意思決定。' },
} as const;

@Component({
  standalone: true,
  imports: [RouterLink, LanguagePickerComponent],
  template: `
    <main class="landing">
      <nav class="landing-nav" [attr.aria-label]="t().mainNavigation">
        <a class="landing-brand" routerLink="/" aria-label="Rubrica"><img src="icons/rubrica-brand/source/rubrica-lockup-primary.png" alt="Rubrica Signature" /></a>
        <div class="landing-links"><a href="#produto">{{ t().navProduct }}</a><a href="#seguranca">{{ t().navSecurity }}</a><a href="#preco">{{ t().navPrice }}</a></div>
        <div class="landing-actions"><app-language-picker /><a class="text-link" routerLink="/login">{{ t().enter }}</a><a class="landing-button small" routerLink="/register">{{ t().start }}</a></div>
      </nav>

      <section class="landing-hero" id="produto">
        <div class="hero-copy"><span class="landing-eyebrow">{{ t().eyebrow }}</span><h1>{{ t().title }}</h1><p>{{ t().lead }}</p><div class="hero-actions"><a class="landing-button" routerLink="/register">{{ t().primary }} <i class="bi bi-arrow-right"></i></a><a class="landing-button outline" href="#como-funciona">{{ t().secondary }}</a></div><div class="micro-trust"><span><i class="bi bi-check-circle-fill"></i> {{ t().freeFive }}</span><span><i class="bi bi-check-circle-fill"></i> {{ t().noCard }}</span><span><i class="bi bi-check-circle-fill"></i> PT · EN · ES · 日本語</span></div></div>
        <div class="hero-visual" [attr.aria-label]="t().flowLabel"><div class="document-demo"><div class="demo-top"><span></span><span></span><span></span></div><div class="demo-line wide"></div><div class="demo-line"></div><div class="demo-line short"></div><div class="demo-stamp"><img src="icons/rubrica-brand/source/rubrica-mark-primary.png" alt="" /><div><small>{{ t().demoSignedBy }}</small><strong>Matheus</strong><span>{{ t().demoHash }}</span></div></div></div><div class="floating-proof"><i class="bi bi-shield-check"></i><span><strong>{{ t().demoIntegrity }}</strong><small>SHA-256</small></span></div></div>
      </section>

      <section class="trust-band" id="seguranca"><img src="icons/rubrica-brand/source/rubrica-mark-primary.png" alt="" /><div><h2>{{ t().trust }}</h2><p>{{ t().trustCopy }}</p></div></section>
      <section class="steps" id="como-funciona"><article><b>01</b><i class="bi bi-file-earmark-arrow-up"></i><h3>{{ t().step1 }}</h3></article><article><b>02</b><i class="bi bi-person-plus"></i><h3>{{ t().step2 }}</h3></article><article><b>03</b><i class="bi bi-patch-check"></i><h3>{{ t().step3 }}</h3></article></section>
      <section class="feature-grid"><article><i class="bi bi-vector-pen"></i><h3>{{ t().feature1 }}</h3></article><article><i class="bi bi-shield-lock"></i><h3>{{ t().feature2 }}</h3></article><article><i class="bi bi-fingerprint"></i><h3>{{ t().feature3 }}</h3></article></section>
      <section class="pricing-section" id="preco">
        <header class="pricing-heading"><span class="landing-eyebrow">RUBRICA</span><h2>{{ t().plans }}</h2><p>{{ t().plansHelp }}</p></header>
        <div class="pricing-grid">
          <article class="price-card"><span class="plan-name">{{ t().base }}</span><p class="plan-price">R$ 29,90 <small>{{ t().perMonth }}</small></p><ul><li><i class="bi bi-check-circle-fill"></i>{{ t().baseFiles }}</li><li><i class="bi bi-check-circle-fill"></i>{{ t().signaturesIncluded }}</li></ul><a class="landing-button outline" routerLink="/register">{{ t().choosePlan }}</a></article>
          <article class="price-card featured"><span class="plan-name">{{ t().intermediate }}</span><p class="plan-price">R$ 69,90 <small>{{ t().perMonth }}</small></p><ul><li><i class="bi bi-check-circle-fill"></i>{{ t().intermediateFiles }}</li><li><i class="bi bi-check-circle-fill"></i>{{ t().professionalAccounts }}</li><li><i class="bi bi-check-circle-fill"></i>{{ t().signaturesIncluded }}</li><li><i class="bi bi-check-circle-fill"></i>{{ t().emailIncluded }}</li></ul><a class="landing-button light" routerLink="/register">{{ t().choosePlan }}</a></article>
          <article class="price-card"><span class="plan-name">{{ t().team }}</span><p class="plan-price">R$ 149,90 <small>{{ t().perMonth }}</small></p><ul><li><i class="bi bi-check-circle-fill"></i>{{ t().teamAccounts }}</li><li><i class="bi bi-check-circle-fill"></i>{{ t().teamAnnual }}</li><li><i class="bi bi-check-circle-fill"></i>{{ t().teamFiles }}</li><li><i class="bi bi-check-circle-fill"></i>{{ t().emailIncluded }}</li></ul><a class="landing-button outline" routerLink="/register">{{ t().choosePlan }}</a></article>
          <article class="price-card enterprise"><span class="plan-name">{{ t().enterprise }}</span><p class="enterprise-copy">{{ t().enterpriseHelp }}</p><ul><li><i class="bi bi-check-circle-fill"></i>{{ t().enterpriseFeature }}</li><li><i class="bi bi-check-circle-fill"></i>{{ t().signaturesIncluded }}</li></ul><a class="landing-button outline" routerLink="/enterprise">{{ t().talkToSales }}</a></article>
        </div>
      </section>
      <section class="final-cta"><img src="icons/rubrica-brand/source/rubrica-mark-primary.png" alt="" /><h2>{{ t().cta }}</h2><a class="landing-button" routerLink="/register">{{ t().primary }}</a></section>
      <section class="supporters-section" aria-labelledby="supporters-title">
        <header><span class="landing-eyebrow">RUBRICA</span><h2 id="supporters-title">{{ t().supporters }}</h2><p>{{ t().supportersHelp }}</p></header>
        <div class="supporters-carousel" aria-label="{{ t().supporters }}">
          <div class="supporters-track">
            <a class="supporter-card" href="https://siboficial.com/" target="_blank" rel="noopener noreferrer" [attr.aria-label]="t().sponsorLink">
              <img src="sponsors/sib/sib-lockup-primary.png" alt="SIB" />
            </a>
          </div>
        </div>
      </section>
      <footer class="landing-footer"><a class="landing-brand" routerLink="/" aria-label="Rubrica"><img src="icons/rubrica-brand/source/rubrica-lockup-primary.png" alt="Rubrica Signature" /></a><nav><a routerLink="/contact">{{ t().contact }}</a><a routerLink="/privacy">{{ t().privacy }}</a><a routerLink="/terms">{{ t().terms }}</a><a routerLink="/data-deletion">{{ t().deletion }}</a></nav><p>© {{ year }} {{ t().rights }}</p></footer>
    </main>
  `,
})
export class LandingPageComponent {
  readonly year = new Date().getFullYear();
  readonly t = computed(() => copy[this.i18n.locale()]);
  constructor(readonly i18n: I18nService, seo: SeoService) { seo.setCanonical('/'); }
}
