import { Component, computed } from '@angular/core';
import { RouterLink } from '@angular/router';

import { I18nService } from '../core/i18n.service';
import { LanguagePickerComponent } from '../components/language-picker.component';
import { SeoService } from '../core/seo.service';

const copy = {
  'pt-BR': { navProduct:'Produto', navSecurity:'Segurança', navPrice:'Preço', enter:'Entrar', start:'Criar conta grátis', eyebrow:'ASSINATURAS SEM COMPLICAÇÃO', title:'Assine documentos com clareza, segurança e validade.', lead:'Envie PDFs, convide signatários e acompanhe cada etapa. As evidências ficam incorporadas ao documento assinado.', primary:'Começar com 5 assinaturas grátis', secondary:'Ver como funciona', trust:'Feito para documentos importantes', trustCopy:'Identidade, data, dispositivo, IP e hash do arquivo reunidos em uma trilha de evidências verificável.', step1:'Envie seu PDF', step2:'Convide as pessoas', step3:'Acompanhe e comprove', feature1:'Carimbo visual no PDF', feature2:'Autenticação em dois fatores', feature3:'Histórico e evidências', plans:'Planos para cada momento', plansHelp:'As assinaturas dos documentos estão incluídas. O limite mensal considera os arquivos enviados pela conta.', base:'Essencial', intermediate:'Profissional', enterprise:'Empresarial', enterpriseHelp:'Uma solução Rubrica adaptada aos processos da sua empresa.', enterpriseFeature:'Fluxo, volume e atendimento personalizados', perMonth:'/mês por conta', currencies:'BRL · USD · EUR · JPY', baseFiles:'Até 20 arquivos por mês', intermediateFiles:'Até 80 arquivos por mês', signaturesIncluded:'Assinaturas eletrônicas incluídas', emailIncluded:'Envio de solicitações por e-mail', choosePlan:'Começar grátis', talkToSales:'Falar com a Rubrica', cta:'Seu próximo documento pode estar assinado hoje.', contact:'Contato', privacy:'Privacidade', terms:'Termos de uso', deletion:'Exclusão de dados', rights:'Rubrica. Documentos assinados, decisões registradas.' },
  en: { navProduct:'Product', navSecurity:'Security', navPrice:'Pricing', enter:'Sign in', start:'Create free account', eyebrow:'SIGNATURES WITHOUT FRICTION', title:'Sign documents with clarity, security and confidence.', lead:'Upload PDFs, invite signers and follow every step. Evidence is embedded into the signed document.', primary:'Start with 5 free signatures', secondary:'See how it works', trust:'Built for important documents', trustCopy:'Identity, date, device, IP and file hash combined into a verifiable evidence trail.', step1:'Upload your PDF', step2:'Invite people', step3:'Track and verify', feature1:'Visual stamp on the PDF', feature2:'Two-factor authentication', feature3:'History and evidence', plans:'Plans for every stage', plansHelp:'Document signatures are included. The monthly allowance counts files uploaded by the account.', base:'Essential', intermediate:'Professional', enterprise:'Enterprise', enterpriseHelp:'A Rubrica solution tailored to your company’s processes.', enterpriseFeature:'Custom workflow, volume and support', perMonth:'/month per account', currencies:'BRL · USD · EUR · JPY', baseFiles:'Up to 20 files per month', intermediateFiles:'Up to 80 files per month', signaturesIncluded:'Electronic signatures included', emailIncluded:'Email signature requests', choosePlan:'Start free', talkToSales:'Talk to Rubrica', cta:'Your next document could be signed today.', contact:'Contact', privacy:'Privacy', terms:'Terms of use', deletion:'Data deletion', rights:'Rubrica. Signed documents, recorded decisions.' },
  es: { navProduct:'Producto', navSecurity:'Seguridad', navPrice:'Precios', enter:'Entrar', start:'Crear cuenta gratis', eyebrow:'FIRMAS SIN COMPLICACIONES', title:'Firma documentos con claridad, seguridad y confianza.', lead:'Sube archivos PDF, invita firmantes y acompaña cada etapa. Las evidencias quedan incorporadas al documento firmado.', primary:'Comenzar con 5 firmas gratis', secondary:'Ver cómo funciona', trust:'Creado para documentos importantes', trustCopy:'Identidad, fecha, dispositivo, IP y hash del archivo reunidos en un registro verificable.', step1:'Sube tu PDF', step2:'Invita a las personas', step3:'Acompaña y comprueba', feature1:'Sello visual en el PDF', feature2:'Autenticación de dos factores', feature3:'Historial y evidencias', plans:'Planes para cada etapa', plansHelp:'Las firmas de documentos están incluidas. El límite mensual cuenta los archivos subidos por la cuenta.', base:'Esencial', intermediate:'Profesional', enterprise:'Empresarial', enterpriseHelp:'Una solución Rubrica adaptada a los procesos de su empresa.', enterpriseFeature:'Flujo, volumen y atención personalizados', perMonth:'/mes por cuenta', currencies:'BRL · USD · EUR · JPY', baseFiles:'Hasta 20 archivos por mes', intermediateFiles:'Hasta 80 archivos por mes', signaturesIncluded:'Firmas electrónicas incluidas', emailIncluded:'Envío de solicitudes por correo', choosePlan:'Comenzar gratis', talkToSales:'Hablar con Rubrica', cta:'Tu próximo documento puede estar firmado hoy.', contact:'Contacto', privacy:'Privacidad', terms:'Términos de uso', deletion:'Eliminación de datos', rights:'Rubrica. Documentos firmados, decisiones registradas.' },
  'ja-JP': { navProduct:'製品', navSecurity:'セキュリティ', navPrice:'料金', enter:'ログイン', start:'無料アカウント作成', eyebrow:'シンプルな電子署名', title:'明確で安全、信頼できる電子署名。', lead:'PDFをアップロードし、署名者を招待して進捗を確認。証拠情報は署名済み文書に組み込まれます。', primary:'無料5件から始める', secondary:'仕組みを見る', trust:'大切な文書のために', trustCopy:'本人情報、日時、端末、IP、ファイルハッシュを検証可能な証拠として記録します。', step1:'PDFを送信', step2:'署名者を招待', step3:'追跡・確認', feature1:'PDF上の署名スタンプ', feature2:'二要素認証', feature3:'履歴と証拠', plans:'用途に合わせたプラン', plansHelp:'文書への電子署名は含まれます。月間上限はアカウントがアップロードしたファイル数です。', base:'エッセンシャル', intermediate:'プロフェッショナル', enterprise:'エンタープライズ', enterpriseHelp:'企業の業務に合わせたRubricaソリューション。', enterpriseFeature:'個別のワークフロー、利用量、サポート', perMonth:'／月・アカウント', currencies:'BRL · USD · EUR · JPY', baseFiles:'月20ファイルまで', intermediateFiles:'月80ファイルまで', signaturesIncluded:'電子署名を含む', emailIncluded:'メールで署名依頼を送信', choosePlan:'無料で始める', talkToSales:'Rubricaに相談', cta:'次の文書を今日署名しませんか。', contact:'お問い合わせ', privacy:'プライバシー', terms:'利用規約', deletion:'データ削除', rights:'Rubrica。署名された文書、記録された意思決定。' },
} as const;

@Component({
  standalone: true,
  imports: [RouterLink, LanguagePickerComponent],
  template: `
    <main class="landing">
      <nav class="landing-nav" aria-label="Principal">
        <a class="landing-brand" routerLink="/" aria-label="Rubrica"><img src="icons/rubrica-mark-name.png" alt="Rubrica Signature" /></a>
        <div class="landing-links"><a href="#produto">{{ t().navProduct }}</a><a href="#seguranca">{{ t().navSecurity }}</a><a href="#preco">{{ t().navPrice }}</a></div>
        <div class="landing-actions"><app-language-picker /><a class="text-link" routerLink="/login">{{ t().enter }}</a><a class="landing-button small" routerLink="/register">{{ t().start }}</a></div>
      </nav>

      <section class="landing-hero" id="produto">
        <div class="hero-copy"><span class="landing-eyebrow">{{ t().eyebrow }}</span><h1>{{ t().title }}</h1><p>{{ t().lead }}</p><div class="hero-actions"><a class="landing-button" routerLink="/register">{{ t().primary }} <i class="bi bi-arrow-right"></i></a><a class="landing-button outline" href="#como-funciona">{{ t().secondary }}</a></div><div class="micro-trust"><span><i class="bi bi-check-circle-fill"></i> 5 grátis</span><span><i class="bi bi-check-circle-fill"></i> Sem cartão</span><span><i class="bi bi-check-circle-fill"></i> PT · EN · ES · 日本語</span></div></div>
        <div class="hero-visual" aria-label="Fluxo de assinatura"><div class="document-demo"><div class="demo-top"><span></span><span></span><span></span></div><div class="demo-line wide"></div><div class="demo-line"></div><div class="demo-line short"></div><div class="demo-stamp"><img src="icons/rubrica-mark.png" alt="" /><div><small>ASSINADO POR</small><strong>Matheus</strong><span>Hash verificado · 14:32</span></div></div></div><div class="floating-proof"><i class="bi bi-shield-check"></i><span><strong>Documento íntegro</strong><small>SHA-256 verificado</small></span></div></div>
      </section>

      <section class="trust-band" id="seguranca"><img src="icons/rubrica-mark.png" alt="" /><div><h2>{{ t().trust }}</h2><p>{{ t().trustCopy }}</p></div></section>
      <section class="steps" id="como-funciona"><article><b>01</b><i class="bi bi-file-earmark-arrow-up"></i><h3>{{ t().step1 }}</h3></article><article><b>02</b><i class="bi bi-person-plus"></i><h3>{{ t().step2 }}</h3></article><article><b>03</b><i class="bi bi-patch-check"></i><h3>{{ t().step3 }}</h3></article></section>
      <section class="feature-grid"><article><i class="bi bi-vector-pen"></i><h3>{{ t().feature1 }}</h3></article><article><i class="bi bi-shield-lock"></i><h3>{{ t().feature2 }}</h3></article><article><i class="bi bi-fingerprint"></i><h3>{{ t().feature3 }}</h3></article></section>
      <section class="pricing-section" id="preco">
        <header class="pricing-heading"><span class="landing-eyebrow">RUBRICA</span><h2>{{ t().plans }}</h2><p>{{ t().plansHelp }}</p></header>
        <div class="pricing-grid">
          <article class="price-card"><span class="plan-name">{{ t().base }}</span><p class="plan-price">R$ 29,90 <small>{{ t().perMonth }}</small></p><ul><li><i class="bi bi-check-circle-fill"></i>{{ t().baseFiles }}</li><li><i class="bi bi-check-circle-fill"></i>{{ t().signaturesIncluded }}</li></ul><a class="landing-button outline" routerLink="/register">{{ t().choosePlan }}</a></article>
          <article class="price-card featured"><span class="plan-name">{{ t().intermediate }}</span><p class="plan-price">R$ 69,90 <small>{{ t().perMonth }}</small></p><ul><li><i class="bi bi-check-circle-fill"></i>{{ t().intermediateFiles }}</li><li><i class="bi bi-check-circle-fill"></i>{{ t().signaturesIncluded }}</li><li><i class="bi bi-check-circle-fill"></i>{{ t().emailIncluded }}</li></ul><a class="landing-button light" routerLink="/register">{{ t().choosePlan }}</a></article>
        </div>
      </section>
      <section class="final-cta"><img src="icons/rubrica-mark.png" alt="" /><h2>{{ t().cta }}</h2><a class="landing-button" routerLink="/register">{{ t().primary }}</a></section>
      <footer class="landing-footer"><a class="landing-brand" routerLink="/" aria-label="Rubrica"><img src="icons/rubrica-mark-name.png" alt="Rubrica Signature" /></a><nav><a routerLink="/contact">{{ t().contact }}</a><a routerLink="/privacy">{{ t().privacy }}</a><a routerLink="/terms">{{ t().terms }}</a><a routerLink="/data-deletion">{{ t().deletion }}</a></nav><p>© {{ year }} {{ t().rights }}</p></footer>
    </main>
  `,
})
export class LandingPageComponent {
  readonly year = new Date().getFullYear();
  readonly t = computed(() => copy[this.i18n.locale()]);
  constructor(readonly i18n: I18nService, seo: SeoService) { seo.setCanonical('/'); }
}
