import { Component, computed } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';

const pages = {
  contato: { eyebrow:'FALE COM A RUBRICA', title:'Contato', intro:'Estamos disponíveis para dúvidas comerciais, suporte e questões sobre privacidade.', sections:[['Atendimento','Envie sua mensagem para contato@rubricasignature.com. Informe o e-mail da conta e, se necessário, o UUID do tenant — nunca envie sua senha.']] },
  privacidade: { eyebrow:'TRANSPARÊNCIA', title:'Política de privacidade', intro:'Tratamos dados pessoais apenas para operar, proteger e comprovar as assinaturas realizadas na plataforma.', sections:[['Dados tratados','Dados da conta, identificadores do documento, IP, navegador, plataforma, data, posição do carimbo e evidências técnicas da assinatura.'],['Finalidade e segurança','Usamos essas informações para autenticação, execução do serviço, prevenção a fraude, auditoria e cumprimento de obrigações legais.'],['Seus direitos','Você pode solicitar acesso, correção ou exclusão pelos nossos canais de contato, observadas as retenções necessárias para preservar documentos assinados e obrigações legais.']] },
  termos: { eyebrow:'REGRAS DO SERVIÇO', title:'Termos de uso', intro:'Ao utilizar o Rubrica, você concorda com estas condições essenciais.', sections:[['Uso responsável','Você deve fornecer informações verdadeiras, proteger suas credenciais e utilizar a plataforma somente para documentos e finalidades lícitas.'],['Assinaturas e evidências','O Rubrica registra evidências técnicas e incorpora informações ao PDF. A adequação jurídica de cada documento e a autorização dos signatários permanecem sob responsabilidade da conta contratante.'],['Disponibilidade e cobrança','Contas novas recebem cinco assinaturas gratuitas. A modalidade paga oferece assinaturas ilimitadas enquanto a assinatura estiver ativa, conforme as condições apresentadas no checkout.']] },
  'exclusao-de-dados': { eyebrow:'CONTROLE DOS SEUS DADOS', title:'Exclusão de dados', intro:'Você pode solicitar a exclusão da sua conta e dos dados pessoais associados.', sections:[['Como solicitar','Envie um e-mail para privacidade@rubricasignature.com usando o endereço cadastrado e informe o UUID do tenant. Confirmaremos sua identidade antes de executar o pedido.'],['O que pode permanecer','Registros necessários para obrigações legais, prevenção a fraude, cobrança ou integridade de documentos assinados podem ser preservados pelo prazo aplicável.'],['Prazo e retorno','Após validar a solicitação, informaremos o escopo da exclusão e o prazo de atendimento pelo mesmo canal.']] },
} as const;

@Component({ standalone:true, imports:[RouterLink], template:`<main class="legal-shell"><nav class="legal-nav"><a class="landing-brand" routerLink="/"><img src="icons/rubrica-mark.png" alt="" /><strong>Rubrica</strong></a><a class="landing-button small" routerLink="/login">Entrar</a></nav><article class="legal-document"><a routerLink="/" class="back-link"><i class="bi bi-arrow-left"></i> Voltar ao início</a><span class="landing-eyebrow">{{ page().eyebrow }}</span><h1>{{ page().title }}</h1><p class="legal-intro">{{ page().intro }}</p>@for(section of page().sections; track section[0]){<section><h2>{{ section[0] }}</h2><p>{{ section[1] }}</p></section>}<small>Última atualização: setembro de 2026.</small></article></main>` })
export class LegalPageComponent { readonly page = computed(() => pages[(this.route.snapshot.data['page'] as keyof typeof pages) ?? 'termos']); constructor(private readonly route: ActivatedRoute) {} }
