import { Routes } from '@angular/router';

import { LandingPageComponent } from './pages/landing-page.component';

export const routes: Routes = [
  { path: '', pathMatch: 'full', component: LandingPageComponent },
  { path: 'contact', loadComponent: () => import('./pages/legal-page.component').then(module => module.LegalPageComponent), data: { page: 'contact' } },
  { path: 'enterprise', loadComponent: () => import('./pages/legal-page.component').then(module => module.LegalPageComponent), data: { page: 'enterprise' } },
  { path: 'privacy', loadComponent: () => import('./pages/legal-page.component').then(module => module.LegalPageComponent), data: { page: 'privacy' } },
  { path: 'terms', loadComponent: () => import('./pages/legal-page.component').then(module => module.LegalPageComponent), data: { page: 'terms' } },
  { path: 'data-deletion', loadComponent: () => import('./pages/legal-page.component').then(module => module.LegalPageComponent), data: { page: 'data-deletion' } },
  { path: 'contato', pathMatch: 'full', redirectTo: 'contact' },
  { path: 'privacidade', pathMatch: 'full', redirectTo: 'privacy' },
  { path: 'termos', pathMatch: 'full', redirectTo: 'terms' },
  { path: 'exclusao-de-dados', pathMatch: 'full', redirectTo: 'data-deletion' },
  { path: 'login', loadComponent: () => import('./pages/login-page.component').then(module => module.LoginPageComponent) },
  { path: 'reactivate-account', loadComponent: () => import('./pages/account-reactivation-page.component').then(module => module.AccountReactivationPageComponent) },
  { path: 'register', loadComponent: () => import('./pages/account-page.component').then(module => module.AccountPageComponent) },
  { path: 'forgot-password', loadComponent: () => import('./pages/account-page.component').then(module => module.AccountPageComponent) },
  { path: 'reset-password', loadComponent: () => import('./pages/account-page.component').then(module => module.AccountPageComponent) },
  { path: 'verify-email', loadComponent: () => import('./pages/account-page.component').then(module => module.AccountPageComponent) },
  { path: 'dashboard', loadComponent: () => import('./pages/dashboard-page.component').then(module => module.DashboardPageComponent) },
  { path: 'a/:accountSlug/dashboard', loadComponent: () => import('./pages/dashboard-page.component').then(module => module.DashboardPageComponent) },
  { path: 't/:tenantSlug/a/:accountSlug/dashboard', loadComponent: () => import('./pages/dashboard-page.component').then(module => module.DashboardPageComponent) },
  { path: 'tenant/a/:tenantAccountId/dashboard', loadComponent: () => import('./pages/dashboard-page.component').then(module => module.DashboardPageComponent) },
  { path: 'tenant/:tenantSlug/dashboard', loadComponent: () => import('./pages/dashboard-page.component').then(module => module.DashboardPageComponent) },
  { path: 'team', loadComponent: () => import('./pages/team-page.component').then(module => module.TeamPageComponent) },
  { path: 'a/:accountSlug/team', loadComponent: () => import('./pages/team-page.component').then(module => module.TeamPageComponent) },
  { path: 't/:tenantSlug/a/:accountSlug/team', loadComponent: () => import('./pages/team-page.component').then(module => module.TeamPageComponent) },
  { path: 'security', loadComponent: () => import('./pages/security-page.component').then(module => module.SecurityPageComponent) },
  { path: 'plan', loadComponent: () => import('./pages/billing-page.component').then(module => module.BillingPageComponent) },
  { path: 'a/:accountSlug/plan', loadComponent: () => import('./pages/billing-page.component').then(module => module.BillingPageComponent) },
  { path: 't/:tenantSlug/a/:accountSlug/plan', loadComponent: () => import('./pages/billing-page.component').then(module => module.BillingPageComponent) },
  { path: 'signing/:token', loadComponent: () => import('./pages/signing-page.component').then(module => module.SigningPageComponent) },
  { path: '**', redirectTo: '' },
];
